/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSV;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        lbl_li1.setVisible(false);
        lbl_li2.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        CheckBox_hide_show_password = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_li1 = new javax.swing.JLabel();
        lbl_li2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb_role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("User name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Password :");

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CheckBox_hide_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_hide_show_passwordActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye-24.png"))); // NOI18N

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/x-mark-24.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login-24.png"))); // NOI18N
        btn_login.setText("Log in");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_li1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_li1.setForeground(new java.awt.Color(255, 102, 0));
        lbl_li1.setText("*");

        lbl_li2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_li2.setForeground(new java.awt.Color(255, 153, 0));
        lbl_li2.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Role :");

        cbb_role.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student", "Teacher", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_username)
                                    .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CheckBox_hide_show_password, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(cbb_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addGap(48, 48, 48)
                                .addComponent(btn_login)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_li1)
                            .addComponent(lbl_li2))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_li1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_li2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox_hide_show_password, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_login))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Nut dang nhap
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       if(txt_username.getText().equals("")){
            lbl_li1.setVisible(true);
        }if(String.valueOf(txt_password.getPassword()).equals("")){
            lbl_li2.setVisible(true);
        }
        else{
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            if(cbb_role.getSelectedItem().equals("Admin")){
                try
            {
                ps = con.prepareStatement("SELECT * FROM users WHERE username = ? AND password = ?");
                ps.setString(1, txt_username.getText());
                ps.setString(2, String.valueOf(txt_password.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
                    MainFormForAdmin mf = new MainFormForAdmin();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    MainFormForAdmin.lbl_username.setText("Welcome<" + txt_username.getText() + ">");
                    MainFormForAdmin.lbl_log.setText("You logged as : Admin");
                    // We will change this with student table
                    MainFormForAdmin.lbl_student_count.setText("Students count = " + Integer.toString(MyFunction.countData("student")));
                    // We will change this with teacher table
                    MainFormForAdmin.lbl_teacher_count.setText("Teachers count = " + Integer.toString(MyFunction.countData("teacher")));
                    // We will change this with course table
                    MainFormForAdmin.lbl_course_count.setText("Courses count = " + Integer.toString(MyFunction.countData("course")));
                    // We will change this with major table
                    MainFormForAdmin.lbl_major_count.setText("Majors count = " + Integer.toString(MyFunction.countData("major")));
                    this.dispose();
                }else{
                    System.out.println("NO");
                }
                } catch (SQLException ex)
            {
                java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
           }if(cbb_role.getSelectedItem().equals("Student")){
               try
            {
                ps = con.prepareStatement("SELECT * FROM student WHERE name = ? AND Email = ?");
                ps.setString(1, txt_username.getText());
                ps.setString(2, String.valueOf(txt_password.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
                    MainFormForStudent mf = new MainFormForStudent();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    MainFormForStudent.lbl_username.setText("Welcome<" + txt_username.getText() + ">");
                    MainFormForStudent.lbl_log.setText("You logged as : Student");
                    // We will change this with student table
                    MainFormForStudent.lbl_student_count.setText("Students count = " + Integer.toString(MyFunction.countData("student")));
                    // We will change this with teacher table
                    MainFormForStudent.lbl_teacher_count.setText("Teachers count = " + Integer.toString(MyFunction.countData("teacher")));
                    // We will change this with course table
                    MainFormForStudent.lbl_course_count.setText("Courses count = " + Integer.toString(MyFunction.countData("course")));
                    // We will change this with major table
                    MainFormForStudent.lbl_major_count.setText("Majors count = " + Integer.toString(MyFunction.countData("major")));
                    this.dispose();
                }else{
                    System.out.println("NO");
                }
                } catch (SQLException ex)
            {
                java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
           }if(cbb_role.getSelectedItem().equals("Teacher")){
               try
            {
                ps = con.prepareStatement("SELECT * FROM teacher WHERE name = ? AND Email = ?");
                ps.setString(1, txt_username.getText());
                ps.setString(2, String.valueOf(txt_password.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
                    MainFormForTeacher mf = new MainFormForTeacher();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    MainFormForTeacher.lbl_username.setText("Welcome<" + txt_username.getText() + ">");
                    MainFormForTeacher.lbl_log.setText("You are logged as : Teacher");
                    // We will change this with student table
                    MainFormForTeacher.lbl_student_count.setText("Students count = " + Integer.toString(MyFunction.countData("student")));
                    // We will change this with teacher table
                    MainFormForTeacher.lbl_teacher_count.setText("Teachers count = " + Integer.toString(MyFunction.countData("teacher")));
                    // We will change this with course table
                    MainFormForTeacher.lbl_course_count.setText("Courses count = " + Integer.toString(MyFunction.countData("course")));
                    // We will change this with major table
                    MainFormForTeacher.lbl_major_count.setText("Majors count = " + Integer.toString(MyFunction.countData("major")));
                    this.dispose();
                }else{
                    System.out.println("NO");
                }
                } catch (SQLException ex)
            {
                java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
           }
            
            
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    // Thoat chuong trinh
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cancelActionPerformed

    // Xem va giau password
    private void CheckBox_hide_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_hide_show_passwordActionPerformed
        // Hide and show Password
        if(CheckBox_hide_show_password.isSelected()){
            txt_password.setEchoChar((char)0);
        }else{
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBox_hide_show_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_hide_show_password;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cbb_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_li1;
    private javax.swing.JLabel lbl_li2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
