/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSV;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class ShowStudent extends javax.swing.JFrame {

    /**
     * Creates new form ShowStudent
     */
    public ShowStudent() {
        initComponents();
        Show_Students_In_JTable();
        setLocationRelativeTo(null);
    }
    
    // Display Data in JTable(hiện thị dữ liệu)
   // 1 - Fill ArrayList with the data(điền dữ liệu)
   public ArrayList<student> getStudentList(){
            ArrayList <student> studentList = new ArrayList<student>();
            Connection con = MyConnection.getConnection();
            String query = "SELECT * FROM student";
            
            Statement st;
            ResultSet rs;
        try
        {                       
            st = con.createStatement();
            rs = st.executeQuery(query);
            
            student std;
            
            while(rs.next()){
                std = new student(rs.getInt("id"), rs.getString("name"), rs.getString("Gender"),
                         rs.getString("Birthdate"), rs.getString("Major"), rs.getString("Address"),
                        rs.getString("Phone_number"), rs.getString("Email"), rs.getBytes("Image"));
                studentList.add(std);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return studentList;
   }
   
   
   
   // 2 - Populate the JTable(điền dữ liệu)
   public void Show_Students_In_JTable(){
       ArrayList<student> list = getStudentList();
       DefaultTableModel model = (DefaultTableModel)tbl_student.getModel();
       // Clear JTable content(xóa nội dung)
       model.setRowCount(0);
       Object[] row = new Object[8];
       for(int i = 0; i < list.size(); i++){
           row[0] = list.get(i).getId();
           row[1] = list.get(i).getName();
           row[2] = list.get(i).getGender();
           row[3] = list.get(i).getBdate();
           row[4] = list.get(i).getMajor();
           row[5] = list.get(i).getAddress();
           row[6] = list.get(i).getPhonename();
           row[7] = list.get(i).getEmail();
           
           model.addRow(row);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_vallfind = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Show Students");

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "Birth date", "Major", "Address", "Phone ", "Email"
            }
        ));
        tbl_student.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentMouseClicked(evt);
            }
        });
        tbl_student.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_studentKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_student);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Values to search :");

        txt_vallfind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_vallfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_vallfindKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_vallfind, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_vallfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentMouseClicked

//        int rowIndex = tbl_student.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel)tbl_student.getModel();
//        txt_id.setText(model.getValueAt(rowIndex, 0).toString());
//        txt_name.setText(model.getValueAt(rowIndex, 1).toString());
//        if(model.getValueAt(rowIndex, 2).toString().equals("male")){
//            rbd_male.setSelected(true);
//            rbd_female.setSelected(false);
//        }else{
//            rbd_female.setSelected(true);
//            rbd_male.setSelected(false);
//        }
//        try
//        {
//
//            Date addDate = null;
//            addDate = new SimpleDateFormat("yyyy-MM-dd").parse((String)getStudentList().get(rowIndex).getBdate());
//            DateChooser_Birthdate.setDate(addDate);
//        } catch (ParseException ex)
//        {
//            Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        cbb_major.setSelectedItem(model.getValueAt(rowIndex, 4).toString());
//        txt_address.setText(model.getValueAt(rowIndex, 5).toString());
//        txt_phone_number.setText(model.getValueAt(rowIndex, 6).toString());
//        txt_email.setText(model.getValueAt(rowIndex, 7).toString());
//        lbl_image.setIcon(ResizeImage(null, getStudentList().get(rowIndex).getPicture()));
    }//GEN-LAST:event_tbl_studentMouseClicked

    private void tbl_studentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_studentKeyReleased
//        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
//            int rowIndex = tbl_student.getSelectedRow();
//            ShowStudent(rowIndex);
//        }
    }//GEN-LAST:event_tbl_studentKeyReleased

    private void txt_vallfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vallfindKeyReleased
        DefaultTableModel model = (DefaultTableModel)tbl_student.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tbl_student.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_vallfind.getText().trim()));
    }//GEN-LAST:event_txt_vallfindKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbl_student;
    private javax.swing.JTextField txt_vallfind;
    // End of variables declaration//GEN-END:variables
}
